export const CANVAS_HEIGHT = 50;
export const INDICATOR_SIZE = 25;
export const CANVAS_ZOOM_RATE = 0.5;
export const LINE_STROKE_MAX_WIDTH = 6;

export const LEFT_LINE_INITIAL_WIDTH = 130;
export const LEFT_INDICATOR_INITIAL_X =
  LEFT_LINE_INITIAL_WIDTH * CANVAS_ZOOM_RATE - INDICATOR_SIZE / 2;

export const CENTER_LINE_INITIAL_WIDTH = 250;
export const RIGHT_INDICATOR_INITIAL_X =
  (LEFT_LINE_INITIAL_WIDTH + CENTER_LINE_INITIAL_WIDTH) * CANVAS_ZOOM_RATE -
  INDICATOR_SIZE / 2;
